"""Kütüphane tabloları eklendi

Revision ID: 22621cfbfa44
Revises: abb863b0af39
Create Date: 2025-10-20 01:22:32.936731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22621cfbfa44'
down_revision = 'abb863b0af39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kullanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('sifre', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('yazar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kitap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.Column('yazar_id', sa.Integer(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.ForeignKeyConstraint(['yazar_id'], ['yazar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odunc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslangic_tarih', sa.DateTime(), nullable=True),
    sa.Column('bitis_tarih', sa.DateTime(), nullable=True),
    sa.Column('iade_tarih', sa.DateTime(), nullable=True),
    sa.Column('kitap_id', sa.Integer(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kitap_id'], ['kitap.id'], ),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ceza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutar', sa.Float(), nullable=True),
    sa.Column('aciklama', sa.String(length=200), nullable=True),
    sa.Column('odunc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['odunc_id'], ['odunc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('ceza')
    op.drop_table('odunc')
    op.drop_table('kitap')
    op.drop_table('yazar')
    op.drop_table('kullanici')
    op.drop_table('kategori')
    # ### end Alembic commands ###
