"""Odunc tablosu güncellendi (teslim_edildi sütunu eklendi)

Revision ID: cbd652569b34
Revises: d051529929e7
Create Date: 2025-11-29 22:35:32.773437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbd652569b34'
down_revision = 'd051529929e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odunc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teslim_edildi', sa.Boolean(), nullable=True))
        batch_op.alter_column('iade_tarih',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('bitis_tarih')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odunc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bitis_tarih', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('iade_tarih',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('teslim_edildi')

    # ### end Alembic commands ###
