"""Ceza tablosu miktar → tutar olarak güncellendi

Revision ID: d051529929e7
Revises: 22621cfbfa44
Create Date: 2025-11-27 03:18:38.739103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd051529929e7'
down_revision = '22621cfbfa44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ceza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tarih', sa.Date(), nullable=True))

    with op.batch_alter_table('odunc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alis_tarihi', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('iade_tarihi', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('teslim_edildi', sa.Boolean(), nullable=True))
        batch_op.drop_column('iade_tarih')
        batch_op.drop_column('baslangic_tarih')
        batch_op.drop_column('bitis_tarih')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odunc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bitis_tarih', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('baslangic_tarih', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('iade_tarih', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('teslim_edildi')
        batch_op.drop_column('iade_tarihi')
        batch_op.drop_column('alis_tarihi')

    with op.batch_alter_table('ceza', schema=None) as batch_op:
        batch_op.drop_column('tarih')

    # ### end Alembic commands ###
